---
title: "Eventos de 2026"
author: "Carlos"
format: html
---

## Allegro e vivace 1

Sala Minas Gerais, 13 de março.
Meu primeiro concerto como assinante da Filarmônica.

* Marisa Rezende: Avessia. É uma peça muito bonita, mas infelizmente não achei nenhuma execução na internet.
* [Corigliano: Concerto para clarinete](https://open.spotify.com/album/6mUI55VjDfO0pId929iff3?si=ga5rtlfHT8mYo4D6yNdCGg). Foi, de longe, a estrela da noite, com o brilhante solo do clarinetista Marcus Lander.
* [Tchaikovsky: Francesca de Rimini, op. 32](https://open.spotify.com/track/0TGhq7cmki9lKgLmVqHm9j?si=34ba636cc5f64c7c).
* [Tchaikovsky: Capricho italiano, op. 45](https://open.spotify.com/track/4HYDsAaLaq6SOSThhe6fNO?si=550db84789794299).


## Concertos para a juventude 1

Sala Minas Gerais, 22 de março.
Foi legal ir na Filarmônica domingo de manhã e ver as jovens famílias lá.
Teve até 'parabéns pra você' pra Araújo.

[Glinka: Abertura de Ruslan e Ludmila](). Peça bonita, não conhecia.
[Beethoven: 1º movimento da Sinfonia nº 9, op. 125]().
[Tchaikovsky: Suíte Mozartiana ou Suíte nº 4 em Sol maior, op. 61]().
[Ravel: Bolero](). Razão pela qual saí de casa, não tenho opinião formada sobre essa peça.


## Concertos da Liberdade: Requeim

Palácio das Artes, 24 de março.
Fui com a intenção de testar a acústica do Plácio das Artes, pois tenho tido problemas para ouvir as peças ali. A plateia superior é, de fato, superior. Os gritos de "Volta, Ligia!" estão cada vez mais frequentes.

* [Wagner: Prelúdio do Ato I de Lohengrin]().
* [Fauré: Cantique de Jean Racine]().
* [Mozart: Réquiem em ré menor](). Sensacional.


## Presto e veloce 2

Sala Minas Gerais, 27 de março.


## Bach nas seguindas

Escola de Música, 30 de março.
